import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ShowserviceService } from 'src/app/showservice.service';

@Component({
  selector: 'app-animation',
  templateUrl: './animation.component.html',
  styleUrls: ['./animation.component.css']
})
export class AnimationComponent {
  constructor(private show :ShowserviceService,private router : Router){
  }
database=this.show.getData();
gotoHere(id:string){
  localStorage.setItem('id',id)
  this.router.navigate(['/single'])
}
anime=[
  {"id":216,"url":"https://www.tvmaze.com/shows/216/rick-and-morty","name":"Rick and Morty","type":"Animation","language":"English","genres":["Comedy","Adventure","Science-Fiction"],"status":"Running","runtime":30,"averageRuntime":30,"premiered":"2013-12-02","ended":null,"officialSite":"http://www.adultswim.com/videos/rick-and-morty","schedule":{"time":"23:00","days":["Sunday"]},"rating":{"average":8.8},"weight":99,"network":
  {"id":10,"name":"Adult Swim","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.adultswim.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":33381,"thetvdb":275274,"imdb":"tt2861424"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/423/1059147.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/423/1059147.jpg","summary":"Rick is a mentally gifted, but sociopathic and alcoholic scientist and a grandfather to Morty; an awkward, impressionable, and somewhat spineless teenage boy. Rick moves into the family home of Morty, where he immediately becomes a bad influence.","updated":1674628442,"_links":{"self":{"href":"https://api.tvmaze.com/shows/216"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2439172"}}},
  {"id":25,"url":"https://www.tvmaze.com/shows/25/hellsing","name":"Hellsing","type":"Animation","language":"Japanese","genres":["Anime","Horror","Supernatural"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2001-10-10","ended":"2002-01-16","officialSite":null,"schedule":{"time":"","days":["Wednesday"]},"rating":{"average":7.6},"weight":85,"network":{"id":131,"name":"Fuji TV","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":9139,"thetvdb":71278,"imdb":"tt0325547"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/178/446544.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/178/446544.jpg","summary":"Hellsing is a 13-part anime based on the manga of the same name. The plot is significantly difficult to that of the the manga although the characters are the same. The show mainly focuses on the hellsing institute that houses the anti-hero named Alucard who swore loyalty to the Helsing family many years before. Alucard being the first ever vampire takes on a new apprentice named Sera's.","updated":1644633501,"_links":{"self":{"href":"https://api.tvmaze.com/shows/25"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/398491"}}},
  {"id":26,"url":"https://www.tvmaze.com/shows/26/hellsing-ultimate","name":"Hellsing Ultimate","type":"Animation","language":"Japanese","genres":["Drama","Action","Anime","Horror"],"status":"Ended","runtime":50,"averageRuntime":50,"premiered":"2006-02-10","ended":"2012-12-26","officialSite":null,"schedule":{"time":"12:00","days":["Wednesday"]},"rating":{"average":7.8},"weight":69,"network":{"id":159,"name":"TBS","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":"https://www.tbs.co.jp/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":29109,"thetvdb":263688,"imdb":"tt0495212"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/178/446780.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/178/446780.jpg","summary":"Hellsing Ultimate, unlike the 13-part <i>Hellsing</i> series, follows the manga of the same name very closely. Alucard being the main protagonist and anti-hero/vampire. <i>Hellsing Ultimate</i> is a 10-part series of OVAs whereby Alucard turns Sera's into a vampire. The main focus of the plot being on an enemy neo-nazi group.","updated":1649863172,"_links":{"self":{"href":"https://api.tvmaze.com/shows/26"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1437"}}},
  {"id":27,"url":"https://www.tvmaze.com/shows/27/berserk","name":"Berserk","type":"Animation","language":"Japanese","genres":["Anime","Fantasy","Horror"],"status":"Ended","runtime":25,"averageRuntime":25,"premiered":"1997-10-07","ended":"1998-03-31","officialSite":null,"schedule":{"time":"","days":["Tuesday"]},"rating":{"average":8.3},"weight":86,"network":{"id":137,"name":"NTV","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":2764,"thetvdb":73752,"imdb":"tt0318871"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/396/991619.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/396/991619.jpg","summary":"Berserk is a 25-part anime set in a dark fantasy/horror environment whereby the series focuses on the main character guts; a lone swordman who later meets up with a group of mercenaries called the band of the hawk. The leader of this band holds a strange necklace called a behelit that will only lead to evil.","updated":1664723201,"_links":{"self":{"href":"https://api.tvmaze.com/shows/27"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1462"}}},
  {"id":40,"url":"https://www.tvmaze.com/shows/40/death-note","name":"Death Note","type":"Animation","language":"Japanese","genres":["Drama","Anime","Thriller","Mystery"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2006-10-03","ended":"2007-06-26","officialSite":"http://www.j-deathnote.com/","schedule":{"time":"13:00","days":["Tuesday"]},"rating":{"average":8.8},"weight":93,"network":{"id":137,"name":"NTV","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":13555,"thetvdb":79481,"imdb":"tt0877057"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/403/1009233.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/403/1009233.jpg","summary":"Death Note is an anime series based around a manga of the same name whereby a human finds a death god's notebook. Any person's name written in this notebook will die. The main character who finds this noteboook is Light Yagami who faces off against an unfaced character named L who tries to challenge him.","updated":1675849418,"_links":{"self":{"href":"https://api.tvmaze.com/shows/40"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1865"}}},
  {"id":117,"url":"https://www.tvmaze.com/shows/117/star-wars-rebels","name":"Star Wars: Rebels","type":"Animation","language":"English","genres":["Action","Adventure","Science-Fiction"],"status":"Ended","runtime":30,"averageRuntime":32,"premiered":"2014-09-29","ended":"2018-03-05","officialSite":"http://disneyxd.disney.com/star-wars-rebels","schedule":{"time":"09:00","days":["Monday"]},"rating":{"average":7.9},"weight":94,"network":
 {"id":25,"name":"Disney XD","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":
 {"id":83,"name":"DisneyNOW","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"dvdCountry":null,"externals":{"tvrage":35995,"thetvdb":283468,"imdb":"tt2930604"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/353/884619.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/353/884619.jpg","summary":"Star Wars Rebels, set five years before the events of Star Wars: Episode IV - A New Hope, tells the story of the Rebellion's beginnings while the Empire spreads tyranny through the galaxy.","updated":1665283589,"_links":{"self":{"href":"https://api.tvmaze.com/shows/117"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1392976"}}},
 {"id":84,"url":"https://www.tvmaze.com/shows/84/family-guy","name":"Family Guy","type":"Animation","language":"English","genres":["Comedy","Family"],"status":"Running","runtime":30,"averageRuntime":30,"premiered":"1999-01-31","ended":null,"officialSite":"http://www.fox.com/family-guy","schedule":{"time":"21:30","days":["Sunday"]},"rating":{"average":7.6},"weight":99,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.fox.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":3506,"thetvdb":75978,"imdb":"tt0182576"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/423/1058269.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/423/1058269.jpg","summary":"Family Guy follows Peter Griffin the endearingly ignorant dad, and his hilariously offbeat family of middle-class New Englanders in Quahog, RI. Lois is Peter's wife, a stay-at-home mom with no patience for her family's antics. Then there are their kids: 18-year-old Meg is an outcast at school and the Griffin family punching bag; 13-year-old Chris is a socially awkward teen who doesn't have a clue about the opposite sex; and one-year-old Stewie is a diabolically clever baby whose burgeoning sexuality is very much a work in progress. Rounding out the Griffin household is Brian the family dog and a ladies' man who is one step away from AA.","updated":1676797919,"_links":{"self":{"href":"https://api.tvmaze.com/shows/84"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2451079"},"nextepisode":{"href":"https://api.tvmaze.com/episodes/2457305"}}},
 
 {"id":107,"url":"https://www.tvmaze.com/shows/107/bobs-burgers","name":"Bob's Burgers","type":"Animation","language":"English","genres":["Comedy","Family"],"status":"Running","runtime":30,"averageRuntime":30,"premiered":"2011-01-09","ended":null,"officialSite":"http://www.fox.com/bobs-burgers","schedule":{"time":"21:00","days":["Sunday"]},"rating":{"average":8.1},"weight":98,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.fox.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":24607,"thetvdb":194031,"imdb":"tt1561755"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/423/1058267.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/423/1058267.jpg","summary":"<p>The series follows Bob who runs <b>Bob's Burgers</b>, with the help of his wife and their three kids. Bob has big ideas about burgers, but the rest of the clan falls short on service. Despite the greasy counters and lousy location, the Belchers are determined to make every \"Grand Re-Re-Re-opening\" a success. Bob's wife, Linda, stands by her man and often does so by bursting into song. Their eldest daughter, 13-year-old Tina has a slight obsession with boys and zombies. Middle child Gene is an aspiring musician with a thirst for life. Louise is the bunny ears-wearing youngest daughter with an off-kilter sense of humor that makes her somewhat of a liability in the kitchen – and with the public.</p>","updated":1676797768,"_links":{"self":{"href":"https://api.tvmaze.com/shows/107"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2453703"},"nextepisode":{"href":"https://api.tvmaze.com/episodes/2466076"}}},

]
}
