import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ShowserviceService } from 'src/app/showservice.service';

@Component({
  selector: 'app-romance',
  templateUrl: './romance.component.html',
  styleUrls: ['./romance.component.css']
})
export class RomanceComponent {
  constructor(private show :ShowserviceService,private router : Router){
  }
database=this.show.getData();
gotoHere(id:string){
  localStorage.setItem('id',id)
  this.router.navigate(['/single'])
}
romance=[
  {"id":3,"url":"https://www.tvmaze.com/shows/3/bitten","name":"Bitten","type":"Scripted","language":"English","genres":["Drama","Horror","Romance"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-01-11","ended":"2016-04-15","officialSite":"http://bitten.space.ca/","schedule":{"time":"22:00","days":["Friday"]},"rating":{"average":7.5},"weight":96,"network":{"id":7,"name":"CTV Sci-Fi Channel","country":{"name":"Canada","code":"CA","timezone":"America/Halifax"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":34965,"thetvdb":269550,"imdb":"tt2365946"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/15.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/15.jpg","summary":"Based on the critically acclaimed series of novels from Kelley Armstrong. Set in Toronto and upper New York State, Bitten follows the adventures of 28-year-old Elena Michaels, the world's only female werewolf. An orphan, Elena thought she finally found her \"happily ever after\" with her new love Clayton, until her life changed forever. With one small bite, the normal life she craved was taken away and she was left to survive life with the Pack.","updated":1665307838,"_links":{"self":{"href":"https://api.tvmaze.com/shows/3"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/631862"}}},
  {"id":8,"url":"https://www.tvmaze.com/shows/8/glee","name":"Glee","type":"Scripted","language":"English","genres":["Drama","Music","Romance"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2009-05-19","ended":"2015-03-20","officialSite":"http://www.fox.com/glee","schedule":{"time":"21:00","days":["Friday"]},"rating":{"average":6.6},"weight":93,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.fox.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":21704,"thetvdb":83610,"imdb":"tt1327801"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/73.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/73.jpg","summary":"Glee is a musical comedy about a group of ambitious and talented young adults in search of strength, acceptance and, ultimately, their voice.","updated":1645378305,"_links":{"self":{"href":"https://api.tvmaze.com/shows/8"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/142185"}}},
  {"id":22,"url":"https://www.tvmaze.com/shows/22/true-blood","name":"True Blood","type":"Scripted","language":"English","genres":["Drama","Romance","Supernatural"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2008-09-07","ended":"2014-08-24","officialSite":"http://www.hbo.com/true-blood","schedule":{"time":"21:00","days":["Sunday"]},"rating":{"average":7.9},"weight":97,"network":{"id":8,"name":"HBO","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.hbo.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":12662,"thetvdb":82283,"imdb":"tt0844441"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/410/1026956.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/410/1026956.jpg","summary":"True Blood is a horror/drama based on a series of novels called <i>The Southern American Vampires Mysteries</i>. It focuses on Sookie Stackhouse and her various encounters with vampires and other supernatural beings. The show is centred in the small town of Bon Temps in Louisiana. The show focuses heavily on the co-existence of humans with vampires. The show also touches on several other controversial issues involving equal rights, violence, discrimination and religion.","updated":1667842963,"_links":{"self":{"href":"https://api.tvmaze.com/shows/22"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1292"}}},
  {"id":43,"url":"https://www.tvmaze.com/shows/43/outlander","name":"Outlander","type":"Scripted","language":"English","genres":["Adventure","Romance","Science-Fiction"],"status":"Running","runtime":60,"averageRuntime":61,"premiered":"2014-08-09","ended":null,"officialSite":"http://www.starz.com/originals/outlander","schedule":{"time":"20:00","days":["Sunday"]},"rating":{"average":8.1},"weight":100,"network":{"id":17,"name":"STARZ","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":36202,"thetvdb":270408,"imdb":"tt3006802"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/436/1091444.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/436/1091444.jpg","summary":"Outlander follows the story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie, a chivalrous and romantic young Scottish warrior, a passionate affair is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives.The <i>Outlander</i> series, adapted from Diana Gabaldon's international best-selling books, spans the genres of romance, science fiction, history and adventure into one epic tale.","updated":1674153690,"_links":{"self":{"href":"https://api.tvmaze.com/shows/43"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2269559"}}},
  {"id":47,"url":"https://www.tvmaze.com/shows/47/witches-of-east-end","name":"Witches of East End","type":"Scripted","language":"English","genres":["Drama","Fantasy","Romance"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2013-10-06","ended":"2014-10-05","officialSite":null,"schedule":{"time":"21:00","days":["Sunday"]},"rating":{"average":7.6},"weight":95,"network":{"id":18,"name":"Lifetime","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":32887,"thetvdb":267259,"imdb":"tt2288064"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/392.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/392.jpg","summary":"Based on Melissa de la Cruz's best-selling novel, Witches of East End centers on the mysterious Beauchamp family who live in the secluded seaside town of East End. Free-spirited artist Joanna Beauchamp is the mother of wild-child bartender Freya and shy librarian Ingrid, who are both gifted -- and cursed -- with a magic birthright, of which they are unaware. Freya notices bizarre occurrences in her life when she inexplicably finds herself drawn to the troubled brother of her wealthy fiance. But it isn't until Joanna's estranged sister appears with a warning that could change the family's fate that the matriarch must reveal to her daughters that they are immortal witches with untapped powers, a revelation that turns their small-town life upside down.","updated":1607931740,"_links":{"self":{"href":"https://api.tvmaze.com/shows/47"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2004"}}},
  {"id":53,"url":"https://www.tvmaze.com/shows/53/nashville","name":"Nashville","type":"Scripted","language":"English","genres":["Drama","Music","Romance"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2012-10-10","ended":"2018-07-26","officialSite":"http://www.cmt.com/shows/nashville/","schedule":{"time":"21:00","days":["Thursday"]},"rating":{"average":7.3},"weight":96,"network":{"id":173,"name":"CMT","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":30808,"thetvdb":259055,"imdb":"tt2281375"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/89/224913.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/89/224913.jpg","summary":"Nashville is set against the backdrop of the city's music scene and follows Rayna Jaymes and Juliette Barnes. Both women face personal and professional challenges as they navigate their paths as artists and individuals. Surrounding them, and often complicating their lives, are their family, friends and, in some cases, lovers, as well as the up-and-coming performers and songwriters trying to get ahead in the business. Music City can mean so many things to different people. In Nashville, musicians and songwriters are at the heart of the storm driven by their own ambitions. Some are fueled by their creativity and passion for fame. Others struggle to cope with the pressures of success and are doing everything in their power to stay on top.","updated":1640930577,"_links":{"self":{"href":"https://api.tvmaze.com/shows/53"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1415712"}}},
  {"id":58,"url":"https://www.tvmaze.com/shows/58/new-girl","name":"New Girl","type":"Scripted","language":"English","genres":["Comedy","Romance"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2011-09-20","ended":"2018-05-15","officialSite":"http://www.fox.com/new-girl/","schedule":{"time":"21:30","days":["Tuesday"]},"rating":{"average":7.2},"weight":96,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.fox.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":28304,"thetvdb":248682,"imdb":"tt1826940"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/145/364581.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/145/364581.jpg","summary":"New Girl is a single-camera ensemble comedy starring Zooey Deschanel as Jess, an offbeat girl who - after a bad breakup - moves in with three single guys and essentially sets a bomb off in their lives.","updated":1657242694,"_links":{"self":{"href":"https://api.tvmaze.com/shows/58"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1430633"}}},
  {"id":62,"url":"https://www.tvmaze.com/shows/62/the-originals","name":"The Originals","type":"Scripted","language":"English","genres":["Drama","Romance","Supernatural"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2013-10-03","ended":"2018-08-01","officialSite":"http://www.cwtv.com/shows/the-originals/","schedule":{"time":"21:00","days":["Wednesday"]},"rating":{"average":8.3},"weight":97,"network":{"id":5,"name":"The CW","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.cwtv.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":34166,"thetvdb":266883,"imdb":"tt2632424"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/156/391233.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/156/391233.jpg","summary":"The Originals is a spin-off show from the supernatural drama <i>The Vampire Diaries</i>. It is based in the city of New Orleans where the originals represent the original vampires. The show is primarily based around conflict between vampires, werewolves and witches in the city.","updated":1599345043,"_links":{"self":{"href":"https://api.tvmaze.com/shows/62"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1390043"}}},
  {"id":63,"url":"https://www.tvmaze.com/shows/63/the-vampire-diaries","name":"The Vampire Diaries","type":"Scripted","language":"English","genres":["Drama","Romance","Supernatural"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2009-09-10","ended":"2017-03-10","officialSite":"http://www.cwtv.com/shows/the-vampire-diaries","schedule":{"time":"20:00","days":["Friday"]},"rating":{"average":8},"weight":97,"network":{"id":5,"name":"The CW","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.cwtv.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":21766,"thetvdb":95491,"imdb":"tt1405406"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/88/220908.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/88/220908.jpg","summary":"The Vampire Diaries is a supernatural drama/romance based around Elena Gilbert who falls in love with a 163 year old vampire.Based on a novel series by L.J. Smith.","updated":1669208065,"_links":{"self":{"href":"https://api.tvmaze.com/shows/63"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1079174"}}},
  {"id":67,"url":"https://www.tvmaze.com/shows/67/greys-anatomy","name":"Grey's Anatomy","type":"Scripted","language":"English","genres":["Drama","Romance","Medical"],"status":"Running","runtime":60,"averageRuntime":60,"premiered":"2005-03-27","ended":null,"officialSite":"https://abc.com/shows/greys-anatomy/","schedule":{"time":"21:00","days":["Thursday"]},"rating":{"average":7.7},"weight":100,"network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://abc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":3741,"thetvdb":73762,"imdb":"tt0413573"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/424/1061065.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/424/1061065.jpg","summary":"The doctors of Grey Sloan Memorial Hospital deal with life-or-death consequences on a daily basis -- it's in one another that they find comfort, friendship and, at times, more than friendship. Together they're discovering that neither medicine nor relationships can be defined in black and white. Real life only comes in shades of grey.","updated":1676704727,"_links":{"self":{"href":"https://api.tvmaze.com/shows/67"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2417098"},"nextepisode":{"href":"https://api.tvmaze.com/episodes/2425601"}}},
  {"id":75,"url":"https://www.tvmaze.com/shows/75/the-mindy-project","name":"The Mindy Project","type":"Scripted","language":"English","genres":["Comedy","Romance","Medical"],"status":"Ended","runtime":null,"averageRuntime":30,"premiered":"2012-09-25","ended":"2017-11-14","officialSite":"http://www.hulu.com/the-mindy-project","schedule":{"time":"","days":["Tuesday"]},"rating":{"average":7.1},"weight":94,"network":null,"webChannel":
{"id":2,"name":"Hulu","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.hulu.com/"},"dvdCountry":null,"externals":{"tvrage":31682,"thetvdb":259007,"imdb":"tt2211129"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/298/745731.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/298/745731.jpg","summary":"The Mindy Project is a single-camera comedy series which follows a skilled OB/GYN navigating the tricky waters of both her personal and professional life.","updated":1667622910,"_links":{"self":{"href":"https://api.tvmaze.com/shows/75"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1334456"}}},

]
}
