import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ShowserviceService } from 'src/app/showservice.service';

@Component({
  selector: 'app-mystery',
  templateUrl: './mystery.component.html',
  styleUrls: ['./mystery.component.css']
})
export class MysteryComponent {
  constructor(private show :ShowserviceService,private router : Router){
  }
database=this.show.getData();
gotoHere(id:string){
  localStorage.setItem('id',id)
  this.router.navigate(['/single'])
}
mystery=[
  {"id":9,"url":"https://www.tvmaze.com/shows/9/revenge","name":"Revenge","type":"Scripted","language":"English","genres":["Drama","Thriller","Mystery"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2011-09-21","ended":"2015-05-10","officialSite":null,"schedule":{"time":"22:00","days":["Sunday"]},"rating":{"average":7.7},"weight":94,"network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://abc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":28387,"thetvdb":248837,"imdb":"tt1837642"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/82/206879.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/82/206879.jpg","summary":"This is not a story about forgiveness; Revenge is a show about retribution. Meet Emily Thorne, the newest resident of The Hamptons. When she was a little girl (and known as Amanda Clarke) her father, David Clarke, was framed for a horrific crime and subsequently sent to prison. While serving his time, the conspirators plotted and murdered David in order to prevent the truth from coming out. Emily is now back with a new identity and ready to take vengeance on the people that murdered her father and stole her childhood.","updated":1676115202,"_links":{"self":{"href":"https://api.tvmaze.com/shows/9"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/154117"}}},
  {"id":39,"url":"https://www.tvmaze.com/shows/39/resurrection","name":"Resurrection","type":"Scripted","language":"English","genres":["Drama","Science-Fiction","Mystery"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-03-09","ended":"2015-01-25","officialSite":null,"schedule":{"time":"21:00","days":["Sunday"]},"rating":{"average":7.1},"weight":90,"network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://abc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":34321,"thetvdb":269650,"imdb":"tt2647586"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/350.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/350.jpg","summary":"The people of Arcadia, Missouri are forever changed when their deceased loved ones suddenly start to reappear. An 8-year-old American boy wakes up alone in a rice paddy in a rural Chinese province with no idea how he got there. Details start to emerge when the boy, who calls himself Jacob, recalls that his hometown is Arcadia, and an Immigration agent, J. Martin Bellamy, takes him there. The home he claims as his own is occupied by a 60-year-old couple, Henry and Lucille Langston, who lost their son, Jacob, more than 30 years ago. While they look different, young Jacob recognizes them as his parents. Lucille is overjoyed at the seeming miracle of her son's reappearance. Henry is reluctant to accept that Jacob is back. Those closest to the family want answers, including Sheriff Fred Langston, whose wife Barbara drowned 30 years ago while trying to save Jacob, and Fred's daughter, Maggie, a local doctor. Pastor Tom Hale seeks a spiritual reason for what's happening in his community. When things take an even more shocking turn, Maggie's life-long friend, Elaine Richards, finds herself drawn into Arcadia's growing mystery. Bellamy, an outsider in the town, joins forces with Maggie to figure out why the unexplainable is happening in Arcadia. As their investigation plays out, Maggie learns some unsettling truths about her own past. Will they be able to solve the mystery of Arcadia before the rest of the world catches on to events there? And will they be able to protect Jacob from forces beyond their control?","updated":1577713566,"_links":{"self":{"href":"https://api.tvmaze.com/shows/39"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/96538"}}},
  {"id":40,"url":"https://www.tvmaze.com/shows/40/death-note","name":"Death Note","type":"Animation","language":"Japanese","genres":["Drama","Anime","Thriller","Mystery"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2006-10-03","ended":"2007-06-26","officialSite":"http://www.j-deathnote.com/","schedule":{"time":"13:00","days":["Tuesday"]},"rating":{"average":8.8},"weight":93,"network":{"id":137,"name":"NTV","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":13555,"thetvdb":79481,"imdb":"tt0877057"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/403/1009233.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/403/1009233.jpg","summary":"Death Note is an anime series based around a manga of the same name whereby a human finds a death god's notebook. Any person's name written in this notebook will die. The main character who finds this noteboook is Light Yagami who faces off against an unfaced character named L who tries to challenge him.","updated":1675849418,"_links":{"self":{"href":"https://api.tvmaze.com/shows/40"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1865"}}},
  {"id":42,"url":"https://www.tvmaze.com/shows/42/sleepy-hollow","name":"Sleepy Hollow","type":"Scripted","language":"English","genres":["Drama","Mystery","Supernatural"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2013-09-16","ended":"2017-03-31","officialSite":"http://www.fox.com/sleepy-hollow","schedule":{"time":"21:00","days":["Friday"]},"rating":{"average":7.5},"weight":96,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.fox.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":34726,"thetvdb":269578,"imdb":"tt2647544"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/81/204166.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/81/204166.jpg","summary":"Sleepy Hollow is a thrilling mystery-adventure drama series spanning two and a half centuries, in which a resurrected Ichabod Crane pairs up with a present-day police lieutenant to save the enigmatic town of Sleepy Hollow--and the world--from unprecedented evil.","updated":1667240048,"_links":{"self":{"href":"https://api.tvmaze.com/shows/42"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1077792"}}},
  {"id":56,"url":"https://www.tvmaze.com/shows/56/chicago-pd","name":"Chicago P.D.","type":"Scripted","language":"English","genres":["Drama","Crime","Mystery"],"status":"Running","runtime":60,"averageRuntime":60,"premiered":"2014-01-08","ended":null,"officialSite":"https://www.nbc.com/chicago-pd","schedule":{"time":"22:00","days":["Wednesday"]},"rating":{"average":8.1},"weight":100,"network":{"id":1,"name":"NBC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.nbc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":35802,"thetvdb":269641,"imdb":"tt2805096"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/426/1065449.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/426/1065449.jpg","summary":"District 21 of the Chicago Police Department is made up of two distinctly different groups. There are the uniformed cops who patrol the beat and go head to head with the city's street crimes. And there's the Intelligence Unit, the team that combats the city's major offenses - organized crime, drug trafficking, high profile murders and beyond. These are their stories.","updated":1676655595,"_links":{"self":{"href":"https://api.tvmaze.com/shows/56"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2470828"},"nextepisode":{"href":"https://api.tvmaze.com/episodes/2478985"}}},
  
]
}
