import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ShowserviceService } from 'src/app/showservice.service';

@Component({
  selector: 'app-comedy',
  templateUrl: './comedy.component.html',
  styleUrls: ['./comedy.component.css']
})
export class ComedyComponent {
  constructor(private show :ShowserviceService,private router : Router){
  }
database=this.show.getData();
gotoHere(id:string){
  localStorage.setItem('id',id)
  this.router.navigate(['/single'])
}
comedy=[
  {"id":216,"url":"https://www.tvmaze.com/shows/216/rick-and-morty","name":"Rick and Morty","type":"Animation","language":"English","genres":["Comedy","Adventure","Science-Fiction"],"status":"Running","runtime":30,"averageRuntime":30,"premiered":"2013-12-02","ended":null,"officialSite":"http://www.adultswim.com/videos/rick-and-morty","schedule":{"time":"23:00","days":["Sunday"]},"rating":{"average":8.8},"weight":99,"network":
  {"id":10,"name":"Adult Swim","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.adultswim.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":33381,"thetvdb":275274,"imdb":"tt2861424"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/423/1059147.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/423/1059147.jpg","summary":"Rick is a mentally gifted, but sociopathic and alcoholic scientist and a grandfather to Morty; an awkward, impressionable, and somewhat spineless teenage boy. Rick moves into the family home of Morty, where he immediately becomes a bad influence.","updated":1674628442,"_links":{"self":{"href":"https://api.tvmaze.com/shows/216"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2439172"}}},
  {"id":28,"url":"https://www.tvmaze.com/shows/28/californication","name":"Californication","type":"Scripted","language":"English","genres":["Drama","Comedy"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2007-08-13","ended":"2014-06-29","officialSite":"http://www.sho.com/sho/californication/home","schedule":{"time":"21:30","days":["Sunday"]},"rating":{"average":7.9},"weight":97,"network":{"id":9,"name":"Showtime","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.sho.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":15319,"thetvdb":80349,"imdb":"tt0904208"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/38/95017.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/38/95017.jpg","summary":"Californication is a series based around the writer Hank Moody. He moves to California and suffers a writers block as well as many other family and personal issues. His drinking and generally unhealthy lifestyle interrupts his relationships with his long term lover Karen and his daughter Becca as he struggles with his manager Charlie Runkle.","updated":1576915629,"_links":{"self":{"href":"https://api.tvmaze.com/shows/28"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1546"}}},
  {"id":32,"url":"https://www.tvmaze.com/shows/32/fargo","name":"Fargo","type":"Scripted","language":"English","genres":["Drama","Comedy","Crime"],"status":"Running","runtime":60,"averageRuntime":68,"premiered":"2014-04-15","ended":null,"officialSite":"http://www.fxnetworks.com/fargo","schedule":{"time":"22:00","days":["Sunday"]},"rating":{"average":8.8},"weight":99,"network":{"id":13,"name":"FX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":35276,"thetvdb":269613,"imdb":"tt2802850"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/267/669639.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/267/669639.jpg","summary":"Fargo is a seasonal anthology crime drama with some dark comical elements, inspired by the film <i>Fargo</i> written by the Coen brothers. Each season follows a new case and new characters, all entrenched in the trademark humor, murder and \"Minnesota nice\" that has made the film an enduring classic.","updated":1659876204,"_links":{"self":{"href":"https://api.tvmaze.com/shows/32"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1922899"}}},
  {"id":41,"url":"https://www.tvmaze.com/shows/41/last-man-standing","name":"Last Man Standing","type":"Scripted","language":"English","genres":["Comedy","Family"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2011-10-11","ended":"2021-05-20","officialSite":"https://www.fox.com/last-man-standing/","schedule":{"time":"21:30","days":["Thursday"]},"rating":{"average":7.8},"weight":96,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.fox.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":28386,"thetvdb":248834,"imdb":"tt1828327"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/419/1049994.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/419/1049994.jpg","summary":"Last Man Standing follows Mike Baxter, a married father of three girls, who tries to maintain his manliness, despite being surrounded by women.","updated":1661513331,"_links":{"self":{"href":"https://api.tvmaze.com/shows/41"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2080865"}}},
  {"id":49,"url":"https://www.tvmaze.com/shows/49/brooklyn-nine-nine","name":"Brooklyn Nine-Nine","type":"Scripted","language":"English","genres":["Comedy","Action","Crime"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2013-09-17","ended":"2021-09-16","officialSite":"https://www.nbc.com/brooklyn-nine-nine","schedule":{"time":"20:00","days":["Thursday"]},"rating":{"average":8.1},"weight":96,"network":{"id":1,"name":"NBC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.nbc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":35774,"thetvdb":269586,"imdb":"tt2467372"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/402/1007484.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/402/1007484.jpg","summary":"Brooklyn Nine-Nine is an ensemble comedy about a talented-but-carefree detective, a by-the-book police captain and their precinct colleagues. While based in the workplace, Brooklyn Nine-Nine is not really about the job – it's about the men and women behind the badge.","updated":1657806173,"_links":{"self":{"href":"https://api.tvmaze.com/shows/49"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2156545"}}},
  {"id":55,"url":"https://www.tvmaze.com/shows/55/red-band-society","name":"Red Band Society","type":"Scripted","language":"English","genres":["Drama","Comedy"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-09-17","ended":"2015-02-07","officialSite":"https://web.archive.org/web/20170615064321/http://www.fox.com/red-band-society","schedule":{"time":"21:00","days":["Wednesday"]},"rating":{"average":7.7},"weight":48,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.fox.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":38923,"thetvdb":281532,"imdb":"tt3576794"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/441.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/441.jpg","summary":"What if a hospital was your high school, boarding school and summer camp rolled into one? What if it was the place where you fell in love for the first time and made friendships that lasted a lifetime? And what if it was all weirdly hilarious and the most fun you ever had in your entire life? This is the world of Red Band Society.","updated":1574895876,"_links":{"self":{"href":"https://api.tvmaze.com/shows/55"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/117709"}}},
  {"id":57,"url":"https://www.tvmaze.com/shows/57/black-ish","name":"black-ish","type":"Scripted","language":"English","genres":["Comedy","Family"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2014-09-24","ended":"2022-04-19","officialSite":"https://abc.com/shows/blackish","schedule":{"time":"21:30","days":["Saturday"]},"rating":{"average":6},"weight":92,"network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://abc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":38317,"thetvdb":281511,"imdb":"tt3487356"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/388/970329.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/388/970329.jpg","summary":"Andre 'Dre' Johnson has a great job, a beautiful wife, Rainbow, four kids, and a colonial home in the 'burbs. But has success brought too much assimilation for this black family? With a little help from his dad, Dre sets out to establish a sense of cultural identity for his family that honors their past while embracing the future.","updated":1658442328,"_links":{"self":{"href":"https://api.tvmaze.com/shows/57"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2293214"}}},
  {"id":58,"url":"https://www.tvmaze.com/shows/58/new-girl","name":"New Girl","type":"Scripted","language":"English","genres":["Comedy","Romance"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2011-09-20","ended":"2018-05-15","officialSite":"http://www.fox.com/new-girl/","schedule":{"time":"21:30","days":["Tuesday"]},"rating":{"average":7.2},"weight":96,"network":{"id":4,"name":"FOX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.fox.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":28304,"thetvdb":248682,"imdb":"tt1826940"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/145/364581.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/145/364581.jpg","summary":"New Girl is a single-camera ensemble comedy starring Zooey Deschanel as Jess, an offbeat girl who - after a bad breakup - moves in with three single guys and essentially sets a bomb off in their lives.","updated":1657242694,"_links":{"self":{"href":"https://api.tvmaze.com/shows/58"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1430633"}}},
  {"id":66,"url":"https://www.tvmaze.com/shows/66/the-big-bang-theory","name":"The Big Bang Theory","type":"Scripted","language":"English","genres":["Comedy"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2007-09-24","ended":"2019-05-16","officialSite":"http://www.cbs.com/shows/big_bang_theory/","schedule":{"time":"20:00","days":["Thursday"]},"rating":{"average":8},"weight":98,"network":{"id":2,"name":"CBS","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.cbs.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":8511,"thetvdb":80379,"imdb":"tt0898266"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/173/433868.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/173/433868.jpg","summary":"The Big Bang Theory is a comedy about brilliant physicists, Leonard and Sheldon, who are the kind of \"beautiful minds\" that understand how the universe works. But none of that genius helps them interact with people, especially women. All this begins to change when a free-spirited beauty named Penny moves in next door. Sheldon, Leonard's roommate, is quite content spending his nights playing Klingon Boggle with their socially dysfunctional friends, fellow Cal Tech scientists Wolowitz and Koothrappali. However, Leonard sees in Penny a whole new universe of possibilities... including love.","updated":1669758304,"_links":{"self":{"href":"https://api.tvmaze.com/shows/66"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1646220"}}},
  {"id":75,"url":"https://www.tvmaze.com/shows/75/the-mindy-project","name":"The Mindy Project","type":"Scripted","language":"English","genres":["Comedy","Romance","Medical"],"status":"Ended","runtime":null,"averageRuntime":30,"premiered":"2012-09-25","ended":"2017-11-14","officialSite":"http://www.hulu.com/the-mindy-project","schedule":{"time":"","days":["Tuesday"]},"rating":{"average":7.1},"weight":94,"network":null,"webChannel":
  {"id":2,"name":"Hulu","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.hulu.com/"},"dvdCountry":null,"externals":{"tvrage":31682,"thetvdb":259007,"imdb":"tt2211129"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/298/745731.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/298/745731.jpg","summary":"The Mindy Project is a single-camera comedy series which follows a skilled OB/GYN navigating the tricky waters of both her personal and professional life.","updated":1667622910,"_links":{"self":{"href":"https://api.tvmaze.com/shows/75"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1334456"}}},

]
}
