import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ShowserviceService } from 'src/app/showservice.service';

@Component({
  selector: 'app-fantasy',
  templateUrl: './fantasy.component.html',
  styleUrls: ['./fantasy.component.css']
})
export class FantasyComponent {
  constructor(private show :ShowserviceService,private router : Router){
  }
database=this.show.getData();
gotoHere(id:string){
  localStorage.setItem('id',id)
  this.router.navigate(['/single'])
}


fantasy=[
  {"id":12,"url":"https://www.tvmaze.com/shows/12/lost-girl","name":"Lost Girl","type":"Scripted","language":"English","genres":["Drama","Fantasy","Horror"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2010-09-12","ended":"2015-10-25","officialSite":"http://www.showcase.ca/lostgirl","schedule":{"time":"22:00","days":["Sunday"]},"rating":{"average":8.1},"weight":93,"network":{"id":6,"name":"Showcase","country":{"name":"Canada","code":"CA","timezone":"America/Halifax"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":26401,"thetvdb":182061,"imdb":"tt1429449"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/137.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/137.jpg","summary":"Lost Girl follows supernatural seductress Bo, a Succubus who feeds on the sexual energy of humans. Growing up with human parents, Bo had no reason to believe she was anything other than the girl next door — until she drained her boyfriend to death in their first sexual encounter. Now she has hit the road alone and afraid. <br /> She discovers she is one of the Fae, creatures of legend and folklore, who pass as humans while feeding off them secretly and in different ways, as they have for millennia. Relieved yet horrified to find out that she is not alone, Bo decides to take the middle path between the humans and the Fae while embarking on a personal mission to unlock the secrets of her origin.With the help of her human sidekick, Kenzi, and Dyson, a sexy police detective, Bo takes on a challenge every week helping a Fae or human client who comes to her to solve a mystery, or to right a wrong.","updated":1665928065,"_links":{"self":{"href":"https://api.tvmaze.com/shows/12"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/316120"}}},
  {"id":23,"url":"https://www.tvmaze.com/shows/23/once-upon-a-time-in-wonderland","name":"Once Upon a Time in Wonderland","type":"Scripted","language":"English","genres":["Drama","Adventure","Fantasy"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2013-10-10","ended":"2014-04-03","officialSite":null,"schedule":{"time":"20:00","days":["Thursday"]},"rating":{"average":6.9},"weight":77,"network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://abc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":35215,"thetvdb":269654,"imdb":"tt2802008"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/73/183661.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/73/183661.jpg","summary":"In Victorian England, the young and beautiful Alice tells a tale of a strange new land that exists on the other side of a rabbit hole. An invisible cat, a hookah smoking caterpillar and playing-cards that talk are just some of the fantastic things she's seen during this impossible adventure. Surely this troubled girl must be insane, and her doctors aim to cure her with a treatment that will make her forget everything. Alice seems ready to put it all behind her, especially the painful memory of the genie she fell in love with and lost forever -- the handsome and mysterious Cyrus . But deep down Alice knows this world is real, and just in the nick of time the sardonic Knave of Hearts and the irrepressible White Rabbit arrive to save her from a doomed fate. Together the trio will take a tumble down the rabbit hole to this Wonderland where nothing is impossible.","updated":1606705379,"_links":{"self":{"href":"https://api.tvmaze.com/shows/23"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1313"}}},
  {"id":27,"url":"https://www.tvmaze.com/shows/27/berserk","name":"Berserk","type":"Animation","language":"Japanese","genres":["Anime","Fantasy","Horror"],"status":"Ended","runtime":25,"averageRuntime":25,"premiered":"1997-10-07","ended":"1998-03-31","officialSite":null,"schedule":{"time":"","days":["Tuesday"]},"rating":{"average":8.3},"weight":86,"network":{"id":137,"name":"NTV","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":2764,"thetvdb":73752,"imdb":"tt0318871"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/396/991619.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/396/991619.jpg","summary":"Berserk is a 25-part anime set in a dark fantasy/horror environment whereby the series focuses on the main character guts; a lone swordman who later meets up with a group of mercenaries called the band of the hawk. The leader of this band holds a strange necklace called a behelit that will only lead to evil.","updated":1664723201,"_links":{"self":{"href":"https://api.tvmaze.com/shows/27"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1462"}}},
  {"id":37,"url":"https://www.tvmaze.com/shows/37/intruders","name":"Intruders","type":"Scripted","language":"English","genres":["Drama","Fantasy","Thriller"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-08-23","ended":"2014-10-11","officialSite":"http://www.bbc.co.uk/programmes/b04nf78f","schedule":{"time":"22:00","days":["Saturday"]},"rating":{"average":6.9},"weight":87,"network":{"id":15,"name":"BBC America","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":38479,"thetvdb":277500,"imdb":"tt3552166"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/126/316698.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/126/316698.jpg","summary":"A contemporary, chilling, paranormal tale set in the moody Pacific Northwest, the series spins a fascinating and complex web of drama. As strange, apparently unrelated events start happening, multiple story-lines - a missing wife, an assassin covering his crimes, a child on the run - begin to intertwine to reveal a conspiracy that will forever change our understanding of human nature.","updated":1574217527,"_links":{"self":{"href":"https://api.tvmaze.com/shows/37"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1808"}}},
  {"id":47,"url":"https://www.tvmaze.com/shows/47/witches-of-east-end","name":"Witches of East End","type":"Scripted","language":"English","genres":["Drama","Fantasy","Romance"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2013-10-06","ended":"2014-10-05","officialSite":null,"schedule":{"time":"21:00","days":["Sunday"]},"rating":{"average":7.6},"weight":95,"network":{"id":18,"name":"Lifetime","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":32887,"thetvdb":267259,"imdb":"tt2288064"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/392.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/392.jpg","summary":"Based on Melissa de la Cruz's best-selling novel, Witches of East End centers on the mysterious Beauchamp family who live in the secluded seaside town of East End. Free-spirited artist Joanna Beauchamp is the mother of wild-child bartender Freya and shy librarian Ingrid, who are both gifted -- and cursed -- with a magic birthright, of which they are unaware. Freya notices bizarre occurrences in her life when she inexplicably finds herself drawn to the troubled brother of her wealthy fiance. But it isn't until Joanna's estranged sister appears with a warning that could change the family's fate that the matriarch must reveal to her daughters that they are immortal witches with untapped powers, a revelation that turns their small-town life upside down.","updated":1607931740,"_links":{"self":{"href":"https://api.tvmaze.com/shows/47"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2004"}}},
  
]
}
