import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ShowserviceService } from 'src/app/showservice.service';

@Component({
  selector: 'app-adventure',
  templateUrl: './adventure.component.html',
  styleUrls: ['./adventure.component.css']
})
export class AdventureComponent {
  constructor(private show :ShowserviceService,private router : Router){
  }
database=this.show.getData();
gotoHere(id:string){
  localStorage.setItem('id',id)
  this.router.navigate(['/single'])
}
advnt=[
  {"id":216,"url":"https://www.tvmaze.com/shows/216/rick-and-morty","name":"Rick and Morty","type":"Animation","language":"English","genres":["Comedy","Adventure","Science-Fiction"],"status":"Running","runtime":30,"averageRuntime":30,"premiered":"2013-12-02","ended":null,"officialSite":"http://www.adultswim.com/videos/rick-and-morty","schedule":{"time":"23:00","days":["Sunday"]},"rating":{"average":8.8},"weight":99,"network":
  {"id":10,"name":"Adult Swim","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.adultswim.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":33381,"thetvdb":275274,"imdb":"tt2861424"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/423/1059147.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/423/1059147.jpg","summary":"Rick is a mentally gifted, but sociopathic and alcoholic scientist and a grandfather to Morty; an awkward, impressionable, and somewhat spineless teenage boy. Rick moves into the family home of Morty, where he immediately becomes a bad influence.","updated":1674628442,"_links":{"self":{"href":"https://api.tvmaze.com/shows/216"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2439172"}}},
  {"id":31,"url":"https://www.tvmaze.com/shows/31/marvels-agents-of-shield","name":"Marvel's Agents of S.H.I.E.L.D.","type":"Scripted","language":"English","genres":["Action","Adventure","Science-Fiction"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2013-09-24","ended":"2020-08-12","officialSite":"http://abc.go.com/shows/marvels-agents-of-shield","schedule":{"time":"22:00","days":["Wednesday"]},"rating":{"average":8},"weight":98,"network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://abc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":32656,"thetvdb":263365,"imdb":"tt2364582"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/142/356776.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/142/356776.jpg","summary":"Phil Coulson heads an elite team of fellow agents with the worldwide law-enforcement organization known as S.H.I.E.L.D. (Strategic Homeland Intervention Enforcement and Logistics Division), as they investigate strange occurrences around the globe. Its members -- each of whom brings a specialty to the group -- work with Coulson to protect those who cannot protect themselves from extraordinary and inconceivable threats.","updated":1661240787,"_links":{"self":{"href":"https://api.tvmaze.com/shows/31"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1839340"}}},
  {"id":6,"url":"https://www.tvmaze.com/shows/6/the-100","name":"The 100","type":"Scripted","language":"English","genres":["Action","Adventure","Science-Fiction"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-03-19","ended":"2020-09-30","officialSite":"http://www.cwtv.com/shows/the-100/","schedule":{"time":"20:00","days":["Wednesday"]},"rating":{"average":7.8},"weight":98,"network":{"id":5,"name":"The CW","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.cwtv.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":34770,"thetvdb":268592,"imdb":"tt2661044"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/257/642675.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/257/642675.jpg","summary":"Ninety-seven years ago, nuclear Armageddon decimated planet Earth, destroying civilization. The only survivors were the 400 inhabitants of 12 international space stations that were in orbit at the time. Three generations have been born in space, the survivors now number 4,000, and resources are running out on their dying \"Ark\" - the 12 stations now linked together and repurposed to keep the survivors alive. Draconian measures including capital punishment and population control are the order of the day, as the leaders of the Ark take ruthless steps to ensure their future, including secretly exiling a group of 100 juvenile prisoners to the Earth's surface to test whether it's habitable.","updated":1666564713,"_links":{"self":{"href":"https://api.tvmaze.com/shows/6"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1913280"}}},
  {"id":18,"url":"https://www.tvmaze.com/shows/18/the-amazing-race","name":"The Amazing Race","type":"Reality","language":"English","genres":["Action","Adventure","Family"],"status":"To Be Determined","runtime":60,"averageRuntime":62,"premiered":"2001-09-05","ended":null,"officialSite":"http://www.cbs.com/shows/amazing_race/","schedule":{"time":"21:00","days":["Wednesday"]},"rating":{"average":7},"weight":96,"network":{"id":2,"name":"CBS","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.cbs.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":5566,"thetvdb":77666,"imdb":"tt0285335"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/423/1058582.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/423/1058582.jpg","summary":"From athletes and actors to tattoo artists, social workers and musicians - a diverse mix of teams will need to utilize their street smarts and savvy know-how to compete in the race of their lifetime.","updated":1670774515,"_links":{"self":{"href":"https://api.tvmaze.com/shows/18"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2430883"}}},
  {"id":23,"url":"https://www.tvmaze.com/shows/23/once-upon-a-time-in-wonderland","name":"Once Upon a Time in Wonderland","type":"Scripted","language":"English","genres":["Drama","Adventure","Fantasy"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2013-10-10","ended":"2014-04-03","officialSite":null,"schedule":{"time":"20:00","days":["Thursday"]},"rating":{"average":6.9},"weight":77,"network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://abc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":35215,"thetvdb":269654,"imdb":"tt2802008"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/73/183661.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/73/183661.jpg","summary":"In Victorian England, the young and beautiful Alice tells a tale of a strange new land that exists on the other side of a rabbit hole. An invisible cat, a hookah smoking caterpillar and playing-cards that talk are just some of the fantastic things she's seen during this impossible adventure. Surely this troubled girl must be insane, and her doctors aim to cure her with a treatment that will make her forget everything. Alice seems ready to put it all behind her, especially the painful memory of the genie she fell in love with and lost forever -- the handsome and mysterious Cyrus . But deep down Alice knows this world is real, and just in the nick of time the sardonic Knave of Hearts and the irrepressible White Rabbit arrive to save her from a doomed fate. Together the trio will take a tumble down the rabbit hole to this Wonderland where nothing is impossible.","updated":1606705379,"_links":{"self":{"href":"https://api.tvmaze.com/shows/23"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1313"}}},
  {"id":43,"url":"https://www.tvmaze.com/shows/43/outlander","name":"Outlander","type":"Scripted","language":"English","genres":["Adventure","Romance","Science-Fiction"],"status":"Running","runtime":60,"averageRuntime":61,"premiered":"2014-08-09","ended":null,"officialSite":"http://www.starz.com/originals/outlander","schedule":{"time":"20:00","days":["Sunday"]},"rating":{"average":8.1},"weight":100,"network":{"id":17,"name":"STARZ","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":36202,"thetvdb":270408,"imdb":"tt3006802"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/436/1091444.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/436/1091444.jpg","summary":"Outlander follows the story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie, a chivalrous and romantic young Scottish warrior, a passionate affair is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives.The <i>Outlander</i> series, adapted from Diana Gabaldon's international best-selling books, spans the genres of romance, science fiction, history and adventure into one epic tale.","updated":1674153690,"_links":{"self":{"href":"https://api.tvmaze.com/shows/43"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2269559"}}},
  {"id":59,"url":"https://www.tvmaze.com/shows/59/chicago-fire","name":"Chicago Fire","type":"Scripted","language":"English","genres":["Drama","Action","Adventure"],"status":"Running","runtime":60,"averageRuntime":60,"premiered":"2012-10-10","ended":null,"officialSite":"https://www.nbc.com/chicago-fire","schedule":{"time":"21:00","days":["Wednesday"]},"rating":{"average":8.1},"weight":100,"network":{"id":1,"name":"NBC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.nbc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":30748,"thetvdb":258541,"imdb":"tt2261391"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/426/1065450.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/426/1065450.jpg","summary":"No job is more stressful, dangerous or exhilarating than those of the Firefighters, Rescue Squad and Paramedics of Chicago Firehouse 51. These are the courageous men and women who forge headfirst into danger when everyone else is running the other way and whose actions make the difference between life and death. These are their stories.","updated":1676799764,"_links":{"self":{"href":"https://api.tvmaze.com/shows/59"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2470830"},"nextepisode":{"href":"https://api.tvmaze.com/episodes/2478986"}}},
  {"id":117,"url":"https://www.tvmaze.com/shows/117/star-wars-rebels","name":"Star Wars: Rebels","type":"Animation","language":"English","genres":["Action","Adventure","Science-Fiction"],"status":"Ended","runtime":30,"averageRuntime":32,"premiered":"2014-09-29","ended":"2018-03-05","officialSite":"http://disneyxd.disney.com/star-wars-rebels","schedule":{"time":"09:00","days":["Monday"]},"rating":{"average":7.9},"weight":94,"network":
  {"id":25,"name":"Disney XD","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":
  {"id":83,"name":"DisneyNOW","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"dvdCountry":null,"externals":{"tvrage":35995,"thetvdb":283468,"imdb":"tt2930604"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/353/884619.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/353/884619.jpg","summary":"Star Wars Rebels, set five years before the events of Star Wars: Episode IV - A New Hope, tells the story of the Rebellion's beginnings while the Empire spreads tyranny through the galaxy.","updated":1665283589,"_links":{"self":{"href":"https://api.tvmaze.com/shows/117"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1392976"}}}
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  ]
}
