import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ShowserviceService } from 'src/app/showservice.service';

@Component({
  selector: 'app-horror',
  templateUrl: './horror.component.html',
  styleUrls: ['./horror.component.css']
})
export class HorrorComponent {
  constructor(private show :ShowserviceService,private router : Router){
  }
database=this.show.getData();
gotoHere(id:string){
  localStorage.setItem('id',id)
  this.router.navigate(['/single'])
}

horror=[
  {"id":3,"url":"https://www.tvmaze.com/shows/3/bitten","name":"Bitten","type":"Scripted","language":"English","genres":["Drama","Horror","Romance"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-01-11","ended":"2016-04-15","officialSite":"http://bitten.space.ca/","schedule":{"time":"22:00","days":["Friday"]},"rating":{"average":7.5},"weight":96,"network":{"id":7,"name":"CTV Sci-Fi Channel","country":{"name":"Canada","code":"CA","timezone":"America/Halifax"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":34965,"thetvdb":269550,"imdb":"tt2365946"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/15.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/15.jpg","summary":"Based on the critically acclaimed series of novels from Kelley Armstrong. Set in Toronto and upper New York State, Bitten follows the adventures of 28-year-old Elena Michaels, the world's only female werewolf. An orphan, Elena thought she finally found her \"happily ever after\" with her new love Clayton, until her life changed forever. With one small bite, the normal life she craved was taken away and she was left to survive life with the Pack.","updated":1665307838,"_links":{"self":{"href":"https://api.tvmaze.com/shows/3"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/631862"}}},
  {"id":12,"url":"https://www.tvmaze.com/shows/12/lost-girl","name":"Lost Girl","type":"Scripted","language":"English","genres":["Drama","Fantasy","Horror"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2010-09-12","ended":"2015-10-25","officialSite":"http://www.showcase.ca/lostgirl","schedule":{"time":"22:00","days":["Sunday"]},"rating":{"average":8.1},"weight":93,"network":{"id":6,"name":"Showcase","country":{"name":"Canada","code":"CA","timezone":"America/Halifax"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":26401,"thetvdb":182061,"imdb":"tt1429449"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/137.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/137.jpg","summary":"Lost Girl follows supernatural seductress Bo, a Succubus who feeds on the sexual energy of humans. Growing up with human parents, Bo had no reason to believe she was anything other than the girl next door — until she drained her boyfriend to death in their first sexual encounter. Now she has hit the road alone and afraid. <br /> She discovers she is one of the Fae, creatures of legend and folklore, who pass as humans while feeding off them secretly and in different ways, as they have for millennia. Relieved yet horrified to find out that she is not alone, Bo decides to take the middle path between the humans and the Fae while embarking on a personal mission to unlock the secrets of her origin.With the help of her human sidekick, Kenzi, and Dyson, a sexy police detective, Bo takes on a challenge every week helping a Fae or human client who comes to her to solve a mystery, or to right a wrong.","updated":1665928065,"_links":{"self":{"href":"https://api.tvmaze.com/shows/12"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/316120"}}},
  {"id":15,"url":"https://www.tvmaze.com/shows/15/constantine","name":"Constantine","type":"Scripted","language":"English","genres":["Drama","Action","Horror"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-10-24","ended":"2015-02-13","officialSite":"https://www.nbc.com/constantine","schedule":{"time":"20:00","days":["Friday"]},"rating":{"average":7.6},"weight":97,"network":{"id":1,"name":"NBC","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.nbc.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":38109,"thetvdb":273690,"imdb":"tt3489184"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/154.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/154.jpg","summary":"Based on the wildly popular comic book series \"Hellblazer\" from DC Comics, seasoned demon hunter and master of the occult John Constantine is armed with a ferocious knowledge of the dark arts and a wickedly naughty wit. He fights the good fight - or at least he did. With his soul already damned to hell, he's decided to abandon his campaign against evil until a series of events thrusts him back into the fray, and he'll do whatever it takes to protect the innocent. With the balance of good and evil on the line, Constantine will use his skills to travel the country, find the supernatural terrors that threaten our world and send them back where they belong. After that, who knows... maybe there's hope for him and his soul after all.","updated":1654193720,"_links":{"self":{"href":"https://api.tvmaze.com/shows/15"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/122719"}}},
  {"id":16,"url":"https://www.tvmaze.com/shows/16/penny-dreadful","name":"Penny Dreadful","type":"Scripted","language":"English","genres":["Horror","Thriller","Supernatural"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-05-11","ended":"2016-06-19","officialSite":"http://www.sho.com/penny-dreadful","schedule":{"time":"21:00","days":["Sunday"]},"rating":{"average":8.3},"weight":96,"network":{"id":9,"name":"Showtime","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.sho.com/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":34172,"thetvdb":265766,"imdb":"tt2628232"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/48/122260.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/48/122260.jpg","summary":"Some of literature's most terrifying characters, including Dr. Frankenstein and his monster, Dorian Gray, and iconic figures from the novel Dracula are lurking in the darkest corners of Victorian London. They are joined by a core of original characters in a complex, frightening new narrative. Penny Dreadful is a psychological thriller filled with dark mystery and suspense, where personal demons from the past can be stronger than vampires, evil spirits and immortal beasts.","updated":1645932817,"_links":{"self":{"href":"https://api.tvmaze.com/shows/16"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/766196"}}},
  {"id":20,"url":"https://www.tvmaze.com/shows/20/the-strain","name":"The Strain","type":"Scripted","language":"English","genres":["Drama","Horror","Thriller"],"status":"Ended","runtime":60,"averageRuntime":61,"premiered":"2014-07-13","ended":"2017-09-17","officialSite":"http://www.fxnetworks.com/thestrain","schedule":{"time":"22:00","days":["Sunday"]},"rating":{"average":7.4},"weight":99,"network":{"id":13,"name":"FX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":33229,"thetvdb":276564,"imdb":"tt2654620"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/444/1111710.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/444/1111710.jpg","summary":"The Strain is a high-concept thriller that tells the story of Dr. Ephraim Goodweather, the head of the Center for Disease Control Canary Team in New York City. He and his team are called upon to investigate a mysterious viral outbreak with hallmarks of an ancient and evil strain of vampirism. As the strain spreads, Goodweather, his team, and an assembly of everyday New Yorkers wage war for the fate of humanity itself.","updated":1675194147,"_links":{"self":{"href":"https://api.tvmaze.com/shows/20"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1128366"}}},
  {"id":25,"url":"https://www.tvmaze.com/shows/25/hellsing","name":"Hellsing","type":"Animation","language":"Japanese","genres":["Anime","Horror","Supernatural"],"status":"Ended","runtime":30,"averageRuntime":30,"premiered":"2001-10-10","ended":"2002-01-16","officialSite":null,"schedule":{"time":"","days":["Wednesday"]},"rating":{"average":7.6},"weight":85,"network":{"id":131,"name":"Fuji TV","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":9139,"thetvdb":71278,"imdb":"tt0325547"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/178/446544.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/178/446544.jpg","summary":"Hellsing is a 13-part anime based on the manga of the same name. The plot is significantly difficult to that of the the manga although the characters are the same. The show mainly focuses on the hellsing institute that houses the anti-hero named Alucard who swore loyalty to the Helsing family many years before. Alucard being the first ever vampire takes on a new apprentice named Sera's.","updated":1644633501,"_links":{"self":{"href":"https://api.tvmaze.com/shows/25"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/398491"}}},
  {"id":26,"url":"https://www.tvmaze.com/shows/26/hellsing-ultimate","name":"Hellsing Ultimate","type":"Animation","language":"Japanese","genres":["Drama","Action","Anime","Horror"],"status":"Ended","runtime":50,"averageRuntime":50,"premiered":"2006-02-10","ended":"2012-12-26","officialSite":null,"schedule":{"time":"12:00","days":["Wednesday"]},"rating":{"average":7.8},"weight":69,"network":{"id":159,"name":"TBS","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":"https://www.tbs.co.jp/"},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":29109,"thetvdb":263688,"imdb":"tt0495212"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/178/446780.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/178/446780.jpg","summary":"Hellsing Ultimate, unlike the 13-part <i>Hellsing</i> series, follows the manga of the same name very closely. Alucard being the main protagonist and anti-hero/vampire. <i>Hellsing Ultimate</i> is a 10-part series of OVAs whereby Alucard turns Sera's into a vampire. The main focus of the plot being on an enemy neo-nazi group.","updated":1649863172,"_links":{"self":{"href":"https://api.tvmaze.com/shows/26"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1437"}}},
  {"id":27,"url":"https://www.tvmaze.com/shows/27/berserk","name":"Berserk","type":"Animation","language":"Japanese","genres":["Anime","Fantasy","Horror"],"status":"Ended","runtime":25,"averageRuntime":25,"premiered":"1997-10-07","ended":"1998-03-31","officialSite":null,"schedule":{"time":"","days":["Tuesday"]},"rating":{"average":8.3},"weight":86,"network":{"id":137,"name":"NTV","country":{"name":"Japan","code":"JP","timezone":"Asia/Tokyo"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":2764,"thetvdb":73752,"imdb":"tt0318871"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/396/991619.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/396/991619.jpg","summary":"Berserk is a 25-part anime set in a dark fantasy/horror environment whereby the series focuses on the main character guts; a lone swordman who later meets up with a group of mercenaries called the band of the hawk. The leader of this band holds a strange necklace called a behelit that will only lead to evil.","updated":1664723201,"_links":{"self":{"href":"https://api.tvmaze.com/shows/27"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1462"}}},
  {"id":30,"url":"https://www.tvmaze.com/shows/30/american-horror-story","name":"American Horror Story","type":"Scripted","language":"English","genres":["Drama","Horror","Thriller"],"status":"Running","runtime":60,"averageRuntime":61,"premiered":"2011-10-05","ended":null,"officialSite":"http://www.fxnetworks.com/shows/american-horror-story","schedule":{"time":"22:00","days":["Wednesday"]},"rating":{"average":7.7},"weight":99,"network":{"id":13,"name":"FX","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":28776,"thetvdb":250487,"imdb":"tt1844624"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/427/1067521.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/427/1067521.jpg","summary":"American Horror Story is an horror television anthology series. Each season is conceived as a self-contained miniseries, following a disparate set of characters and settings, and a storyline with its own beginning, middle, and end. While some actors appear for more than one year, they play completely different roles in each season.","updated":1675616179,"_links":{"self":{"href":"https://api.tvmaze.com/shows/30"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2402175"}}},
  {"id":33,"url":"https://www.tvmaze.com/shows/33/hemlock-grove","name":"Hemlock Grove","type":"Scripted","language":"English","genres":["Drama","Horror","Thriller"],"status":"Ended","runtime":null,"averageRuntime":52,"premiered":"2013-04-19","ended":"2015-10-23","officialSite":"https://www.netflix.com/title/70242310","schedule":{"time":"","days":[]},"rating":{"average":7},"weight":92,"network":null,"webChannel":{"id":1,"name":"Netflix","country":null,"officialSite":"https://www.netflix.com/"},"dvdCountry":null,"externals":{"tvrage":33272,"thetvdb":259948,"imdb":"tt2309295"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/0/305.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/0/305.jpg","summary":"Secrets are just a part of daily life in the small Pennsylvania town of Hemlock Grove, where the darkest evils hide in plain sight.","updated":1653908270,"_links":{"self":{"href":"https://api.tvmaze.com/shows/33"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/393772"}}},
  {"id":34,"url":"https://www.tvmaze.com/shows/34/helix","name":"Helix","type":"Scripted","language":"English","genres":["Horror","Science-Fiction","Thriller"],"status":"Ended","runtime":60,"averageRuntime":60,"premiered":"2014-01-10","ended":"2015-04-10","officialSite":null,"schedule":{"time":"22:00","days":["Friday"]},"rating":{"average":6.6},"weight":91,"network":{"id":16,"name":"Syfy","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":34277,"thetvdb":265912,"imdb":"tt2758950"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/126/316697.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/126/316697.jpg","summary":"Helix is a science fiction thriller that focuses on a CDC expedition into the arctic. They go there to investigate the potential outbreak of a disease with no idea what they are getting themselves into. They encounter an almost zombie-like threat that could threaten mankind itself whilst the operator of the facility seems to know more than what he is saying.","updated":1675535623,"_links":{"self":{"href":"https://api.tvmaze.com/shows/34"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/143215"}}},
  {"id":38,"url":"https://www.tvmaze.com/shows/38/z-nation","name":"Z Nation","type":"Scripted","language":"English","genres":["Action","Horror","Science-Fiction"],"status":"Ended","runtime":60,"averageRuntime":61,"premiered":"2014-09-12","ended":"2018-12-28","officialSite":"http://www.syfy.com/znation","schedule":{"time":"21:00","days":["Friday"]},"rating":{"average":7.2},"weight":94,"network":{"id":16,"name":"Syfy","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":null},"webChannel":null,"dvdCountry":null,"externals":{"tvrage":41883,"thetvdb":280494,"imdb":"tt3843168"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/170/426759.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/170/426759.jpg","summary":"Z Nation starts three years after the zombie virus has gutted the country, a team of everyday heroes must transport the only known survivor of the plague from New York to California, where the last functioning viral lab waits for his blood. Although the antibodies he carries are the world's last, best hope for a vaccine, he hides a dark secret that threatens them all. With humankind's survival at stake, the ragtag band embarks on a journey of survival across three thousand miles of rusted-out post-apocalyptic America.","updated":1661551029,"_links":{"self":{"href":"https://api.tvmaze.com/shows/38"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/1578229"}}},
  {"id":73,"url":"https://www.tvmaze.com/shows/73/the-walking-dead","name":"The Walking Dead","type":"Scripted","language":"English","genres":["Drama","Action","Horror"],"status":"Ended","runtime":null,"averageRuntime":62,"premiered":"2010-10-31","ended":"2022-11-20","officialSite":"https://www.amc.com/twdu/the-walking-dead","schedule":{"time":"","days":["Sunday"]},"rating":{"average":8},"weight":100,"network":null,"webChannel":
  {"id":453,"name":"AMC+","country":{"name":"United States","code":"US","timezone":"America/New_York"},"officialSite":"https://www.amcplus.com/"},"dvdCountry":null,"externals":{"tvrage":25056,"thetvdb":153021,"imdb":"tt1520211"},"medium":"https://static.tvmaze.com/uploads/images/medium_portrait/424/1061900.jpg","original":"https://static.tvmaze.com/uploads/images/original_untouched/424/1061900.jpg","summary":"The Walking Dead tells the story of the months and years that follow after a zombie apocalypse. It follows a group of survivors, led by former police officer Rick Grimes, who travel in search of a safe and secure home. As the world overrun by the dead takes its toll on the survivors, their interpersonal conflicts present a greater danger to their continuing survival than the walkers that roam the country. Over time, the characters are changed by the constant exposure to death and some grow willing to do anything to survive.Based on the comic book series of the same name by Robert Kirkman, Tony Moore, and Charlie Adlard.","updated":1669133052,"_links":{"self":{"href":"https://api.tvmaze.com/shows/73"},"previousepisode":{"href":"https://api.tvmaze.com/episodes/2408243"}}},

]

}
